<<<<<<< HEAD
# Generated by Django 3.1.3 on 2021-03-24 18:34
=======
# Generated by Django 3.1.3 on 2020-12-20 22:31
>>>>>>> fa9bec0 (fifth commit)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
<<<<<<< HEAD
            field=models.TextField(default=''),
=======
            field=models.TextField(default='', blank=True),
>>>>>>> fa9bec0 (fifth commit)
        ),
    ]
